CREATE DATABASE CS8120;

USE `CS8120`;

CREATE TABLE `USER` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(32) NOT NULL,
	`SALT` INT NOT NULL,
	`PASSWORD` CHAR(224) NOT NULL,
	`PRIVILEGE` INT NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `FILE` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
	`NAME` VARCHAR(32) NOT NULL,
	`CONTENT` TEXT,
	PRIMARY KEY (`ID`),
	FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
);